# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ozinshe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Localize-Swift', '~> 3.2'
pod 'Alamofire'
pod 'SVProgressHUD'
pod 'SDWebImage', '~> 5.0'
pod 'SwiftyJSON', '~> 4.0'



  # Pods for Ozinshe

end
